name: ci
# only deploy site from master branch
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # run all tests straight from Markdown files
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v1
        with:
          config: video=false

      - name: Check links ⚓️
        run: npm run check:links

      - name: Build site 🏗
        run: npm run docs:build

      - name: Copy built site 🚛
        run: npm run cp:dist

      - name: Export Markdown specs 🖨
        run: ./md-to-js.sh http://localhost:5000/cypress-examples

      - name: Test built site 🧪
        uses: cypress-io/github-action@v1
        with:
          start: npm run serve:public
          config-file: cypress-dist.json
          config: baseUrl=http://localhost:5000/cypress-examples

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
