# Scrape deployed site into Algolia index
# https://glebbahmutov.com/blog/scrape-static-site-with-algolia/
name: deployed
on:
  status:
    branches:
      - master
jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event 🖨
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Print the context 📋
        run: echo "context ${{ github.event.context }} state ${{ github.event.state }}"

  test-publish-scrape:
    if: github.event.context == 'github/pages' && github.event.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "gh-pages 📑 deployed successfully ✅"

      # we need our scraping config, thus check out code
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false

      - name: Set Cypress version 🎁
        id: cypress
        run: echo "::set-output name=version::$(node ./src/print-cypress-version)"

      - name: Print Cypress version 🖨
        run: echo "Cypress version is ${{ steps.cypress.outputs.version }}"

      - name: Export Markdown specs 🖨
        run: node ./md-to-js https://glebbahmutov.com/cypress-examples/${{ steps.cypress.outputs.version }}

      - name: Catch stray .only tests 🚦
        run: npm run stop-only

      - name: Format extracted specs 💅
        run: npm run format:extracted

      # we "simulate" Run All Specs button in Test Runner GUI
      # by concatenating all extracted specs into a single one
      # to be included in the test run.
      # Note: delete this file before publishing to NPM
      - name: Create Run All Spec 🏗
        run: cat docs/**/*.js > docs/run-all-specs.js

      - name: Test deployed site 🧪💨
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          config-file: cypress-dist.json
          record: true
          tag: deployed
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.recordKey }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete run all specs file 🗑
        run: rm docs/run-all-specs.js

      # by including "cypress.json" with bare settings
      # users who install this package from NPM can run the specs
      # using
      #   npm i -D @bahmutov/cypress-examples
      #   npx cypress open --project node_modules/\@bahmutov/cypress-examples
      - name: Include cypress-npm.json 🏗
        run: cp cypress-npm.json cypress.json

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update Algolia config 📝
        run: node ./update-algolia-config https://glebbahmutov.com/cypress-examples/${{ steps.cypress.outputs.version }}

      # when scraping the site, inject secrets as environment variables
      # then pass their values into the Docker container using "-e" syntax
      # and inject config.json contents as another variable
      - name: scrape the site 🧽
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker run \
          -e APPLICATION_ID -e API_KEY \
          -e CONFIG="$(cat algolia-config.json)" \
          algolia/docsearch-scraper:v1.6.0
