# Scrape deployed site into Algolia index
# https://glebbahmutov.com/blog/scrape-static-site-with-algolia/
name: deployed
on:
  status:
    branches:
      - master
jobs:
  scraped-site:
    if: github.event.context == 'github/pages' && github.event.state == 'success'
    runs-on: ubuntu-latest
    env:
      CYPRESS_baseUrl: https://glebbahmutov.com/cypress-examples
    steps:
      - run: echo "gh-pages 📑 built successfully ✅"

      # we need our scraping config, thus check out code
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies 📦
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false

      - name: Export Markdown specs 🖨
        run: |
          npx export-fiddle docs/commands/actions.md --before $CYPRESS_baseUrl/commands/actions
          npx export-fiddle docs/commands/connectors.md --before $CYPRESS_baseUrl/commands/connectors
          npx export-fiddle docs/commands/querying.md --before $CYPRESS_baseUrl/commands/querying
          npx export-fiddle docs/commands/traversal.md --before $CYPRESS_baseUrl/commands/traversal
          ls -laR docs/**/*.js

        - name: Test deployed site 🧪
          uses: cypress-io/github-action@v1
          with:
            # we have already installed all dependencies above
            install: false
            config-file: cypress-dist.json

      # when scraping the site, inject secrets as environment variables
      # then pass their values into the Docker container using "-e" syntax
      # and inject config.json contents as another variable
      - name: scrape the site 🧽
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker run \
          -e APPLICATION_ID -e API_KEY \
          -e CONFIG="$(cat algolia-config.json)" \
          algolia/docsearch-scraper:v1.6.0
